/*
Given a string containing of ‘0’, ‘1’
and ‘?’ wildcard characters, generate all binary strings
that can be formed by replacing each wildcard character by ‘0’ or ‘1’.

Input Format
The first line of input contains a single integer T denoting
the number of test cases. Then T test cases follow. Each test case
consist of two lines. The first line of each test case consists of a string S.

Constraints
1 ≤ T ≤ 60 1 ≤ length of string S ≤ 30

Output Format
Print all binary string that can be formed by replacing
each wildcard character separated by space.

Sample Input
1
1??0?101
Sample Output
10000101 10001101 10100101 10101101 11000101 11001101 11100101 11101101
Explanation
For the Given test case, 10000101 can be generated by replacing
wildcard character from 1??0?101 by 0s.
*/

#include <iostream>
using namespace std;

void print(string str, int index)
{
    if (index == str.size())
    {
        cout << str << " ";
        return;
    }

    if (str[index] == '?')
    {
        // replace '?' by '0' and recurse
        str[index] = '0';
        print(str, index + 1);

        // replace '?' by '1' and recurse
        str[index] = '1';
        print(str, index + 1);
    }
    else
        print(str, index + 1);
}

// Driver code to test above function
int main()
{
    int n;
    cin >> n;
    for (int i = 0; i < n; i++)
    {
        string str;
        cin >> str;
        print(str, 0);
        cout << endl;
    }

    return 0;
}